### ISSUE TITLE
Starter Template is broken

### ISSUE THREAD

**Issue by SebasG22** [thirdweb-example/vite-typescript-starter#1]
The starter template is broken due to dependency `fetch`: 
```bash
index.js:504 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at node_modules/nofilter/lib/index.js (index.js:504:11)
    at __require2 (chunk-FKZU6AN4.js?v=74759e5a:47:50)
    at node_modules/cbor/lib/utils.js (utils.js:4:18)
    at __require2 (chunk-FKZU6AN4.js?v=74759e5a:47:50)
    at node_modules/cbor/lib/commented.js (commented.js:4:15)
    at __require2 (chunk-FKZU6AN4.js?v=74759e5a:47:50)
    at node_modules/cbor/lib/cbor.js (cbor.js:3:21)
    at __require2 (chunk-FKZU6AN4.js?v=74759e5a:47:50)
    at esm_shims.js:2:32
```

This also broke the cloud version  https://vite-typescript-starter.thirdweb-example.com/

**Comment by jnsdls** [comment]
hey @SebasG22, thanks for the report. We're actively working on a fix for this in: https://github.com/thirdweb-dev/typescript-sdk/pull/459 and will update this template when that is resolved later today!

**Comment by SebasG22** [comment]
> hey @SebasG22, thanks for the report. We're actively working on a fix for this in: [thirdweb-dev/typescript-sdk#459](https://github.com/thirdweb-dev/typescript-sdk/pull/459) and will update this template when that is resolved later today!
@jnsdls 
I confirm this fix solves the blocker issue. Now the button to connect to Metamask is on the screen. The only issue that I saw is an error for Buffer.
![image](https://user-images.githubusercontent.com/17608169/172852083-9fe39f03-f7a6-4c5f-99ab-cfaf3832ced2.png)
